fix m1
smallcloudai/refact-lsp pull request #102
Opened 2024-02-25 17:00 UTC by reymondzzzz

2024-02-26 16:15 UTC, valaises commented on Cargo.toml
> +lance-index = { git = "https://github.com/lancedb/lance.git", branch = "main"}
we should remove it as soon as lance updates its crates

2024-02-26 16:17 UTC, valaises commented on src/vecdb/handler.rs
> +            .search(&*embedding.clone())
Scary

2024-02-26 16:18 UTC, valaises approved these changes

2024-02-26 16:20 UTC, valaises requested changes
I don't like unwrap

2024-02-26 16:25 UTC, valaises commented
![image](https://github.com/smallcloudai/refact-lsp/assets/43416739/c2754192-649c-4368-9027-78f2ff5a52cf)
Why do you need `&*` here?

2024-02-27 06:51 UTC, JegernOUTT approved these changes

2024-02-27 07:27 UTC, closed without merging