Context Format for Prompt for Completion & friends
smallcloudai/refact-lsp pull request #126
Opened 2024-04-02 17:39 UTC by valaises

2024-04-02 22:45 UTC, valaises commented on src/scratchpads/completion_single_file_fim.rs
> +        info!("patch: {}", patch);
shit, gotta remove this one 😁

2024-04-03 06:47 UTC, olegklimov commented on src/scratchpad_abstract.rs
>  }
`supports_context` -> `context_style`, a string

2024-04-03 06:48 UTC, olegklimov commented on src/scratchpad_abstract.rs
>  }
n_ctx why do we need one over there?

2024-04-03 06:55 UTC, olegklimov commented on src/scratchpads/completion_single_file_fim.rs
> +        let prompt_tokens_before_context = self.t.count_tokens(prompt.as_str())?;
Do we really need that? Encoding text is a long operation. We don't have a counter above?

2024-04-03 06:57 UTC, olegklimov commented on src/scratchpads/chat_utils_rag.rs
> +        "was_looking_for": was_looking_for.clone(),
"was_looking_for":  [
  {"symbol": "xxx", "something_else": 1337},
  {"symbol": "xxx", "something_else": 1337},
  {"symbol": "xxx", "something_else": 1337}
  ]

2024-04-03 10:06 UTC, JegernOUTT requested changes

2024-04-03 10:06 UTC, JegernOUTT commented on src/ast/ast_module.rs
> +            info!("found {last_30_chars}");
those are not found, but parsed near the cursor

2024-04-03 10:06 UTC, JegernOUTT commented on src/ast/ast_module.rs
> +        let was_looking_for = cursor_usages.iter().chain(declarations.iter()).chain(usages.iter()).map(|x|last_n_chars(&x.name, 30)).collect::<Vec<_>>();
Do we really need that here?
We can take symbol names afterward

2024-04-04 04:40 UTC, JegernOUTT requested changes

2024-04-04 04:40 UTC, JegernOUTT commented on src/scratchpads/completion_single_file_fim.rs
> +            self.post.rag_tokens_n.min(2048).max(1024)
Can we get rid of all hardcoded context sizes?

2024-04-04 04:40 UTC, JegernOUTT commented on src/ast/ast_module.rs
> +        let mut was_looking_for = HashMap::new();
move `was_looking_for` outside this function

2024-04-04 04:40 UTC, JegernOUTT commented on src/scratchpads/completion_single_file_fim.rs
> +    if context_format == "starcoder" {
Add a default `context_format`
If you cannot figure out which format is the best - just wrap all the code with the comments (see `wrap_comments`) and put it above the prefix part of the code

2024-04-04 05:05 UTC, merged