At-File command enhancements
smallcloudai/refact-lsp pull request #91
Opened 2024-02-20 14:47 UTC by valaises

2024-02-21 10:52 UTC, JegernOUTT requested changes

2024-02-21 10:52 UTC, JegernOUTT commented on src/at_commands/at_file.rs
> +        &format!("file://{}", file_path) // TODO: maybe there's a better way to do this?
look for
```
pathbuf_to_url
```

2024-02-21 10:52 UTC, JegernOUTT commented on src/vecdb/vectorizer_service.rs
> +    let b_size = 32; // TODO: I'm not sure b_size is useful, should drop it
It was working before without this weird code
What is the reason it's broken now?

2024-02-22 05:49 UTC, JegernOUTT requested changes

2024-02-22 05:49 UTC, JegernOUTT commented on src/at_commands/at_params.rs
> +        .map(|f|f.replace("file://", ""))// TODO: maybe there's a better way to do this?
pathbuf_to_url

2024-02-22 13:03 UTC, olegklimov approved these changes

2024-02-22 13:03 UTC, merged